branch-defaults:
  rel-v1.0:
<<<<<<< HEAD
    environment: null
global:
  application_name: eCommerceAPI
  default_ec2_keyname: awstlahui
  default_platform: PHP 5.6
=======
    environment: tlahui-dev
global:
  application_name: eCommerceAPI
  default_ec2_keyname: awstlahui
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running PHP 5.6
>>>>>>> development
  default_region: us-west-2
  profile: tlahui
  sc: git
